[build]
  command = "yarn build"
  publish = "build"

[context.production.environment]
  REACT_APP_BACKENDURL ="https://backend-olichange.herokuapp.com/api/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
